# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.3.3
  amd64: ghcr.io/hassio-addons/base:14.3.3
  armhf: ghcr.io/hassio-addons/base:14.3.3
  armv7: ghcr.io/hassio-addons/base:14.3.3
  i386: ghcr.io/hassio-addons/base:14.3.3
labels:
  org.opencontainers.image.title: "Snapcast-server add-on"
  org.opencontainers.image.description: "Snapcast server Add-on with Spotify connect support."
  org.opencontainers.image.source: "https://github.com/corneyl/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
